### PR TITLE
Better versionnumbers

### PR DESCRIPTION
**Pull request by kolewu**
Here is my proposal for #35 .

With this change the version information is derived from the `build-version.cmake` file and -- if available -- repository information (commit hash and dirty flag). It only affects the dependent files when something changes, so no unnecessary builds, even if the version number in `build-version.cmake` is changed.

The second change parses the version number from `git describe` including the patch version and updates the appropriate files.

### CODE REVIEW

**Comment by cecilios** [comment]
Great! Thank you. 
A question: why to create helper.sh instead of putting its code inside update-version.sh? Do you prefer to have functions apart just in case they can be useful in other scripts?

**Comment by kolewu** [comment]
I put them into an extra file to make them testable. With the extra file you can do this very easily:

    for d in "0.17.20-0-g0d8f9a3" "0.17.20-2-g25fd5cc" "0.17" "error"
    do
        parseDescription "$d"
        echo
    done

It should be a real test, but to make sure the implementation works the same as the one before, it's sufficient.

**Comment by cecilios** [comment]
Thank you. Merged.

**Comment by cecilios** [comment]
Closes #35

**Pull request merged**
